### PR TITLE
Default Prefix is now optional in Wrapper

### PR DESCRIPTION
**Pull request by EvolutionX-10**

### CODE REVIEW

**Review by jacoobes — CHANGES_REQUESTED** [review]
can you check strictly, defaultPrefix === undefined is preferred, as its the style in the rest of the project

**Comment by EvolutionX-10** [comment]
> can you check strictly, defaultPrefix === undefined is preferred, as its the style in the rest of the project

so this?
```ts
if (typeof defaultPrefix === 'undefined') return;
```

**Comment by jacoobes** [comment]
if(defaultPrefix === undefined) return;

**Comment by EvolutionX-10** [comment]
alr

**Review by jacoobes — APPROVED** [review]

**Pull request merged**
